language: node_js
node_js:
- "7"
cache:
  directories:
  - node_modules # NPM packages
  - $(npm config get prefix)/bin/gulp
  - $(npm config get prefix)/bin/firebase
  - /home/travis/.local/bin
install:
- npm install -g gulp
- npm install -g firebase-tools
- npm install
script:
- npm run build
after_success:
- 'if [ "${TRAVIS_BRANCH}" = "production" ]; then firebase deploy --non-interactive --token "$FIREBASE_TOKEN" --project ampstart-8dc54; fi'
- 'if [ "${TRAVIS_BRANCH}" = "master" ]; then firebase deploy --non-interactive --token "$FIREBASE_TOKEN" --project ampstart-staging; fi'
branches:
  only:
  - production
  - master
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
