/**
 * Copyright 2019 The AMP HTML Authors. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS-IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import * as React from 'react';
import {AmpIncludeCustomElement} from '../../src-gen/';
import {AmpScriptProps} from 'src-gen/amp.d';

/**
 * Embeds an AMP Script by either linking to a JS `src` file or embedding inline
 * AMP Script via the `script` property. The inline script hash will automatically
 * be generated by AMP Optimizer.
 */
const AmpScript: React.FunctionComponent<AmpScriptProps & {className?: string}> = ({
  id,
  className,
  script,
  children,
  ...props
}) => {
  return (
    <>
      <AmpIncludeCustomElement name='amp-script' />
      <amp-script script={id} class={className} {...props}>
        {children}
      </amp-script>
      {script && (
        <script
          id={id}
          type='text/plain'
          target='amp-script'
          dangerouslySetInnerHTML={{
            __html: generateInlineScript(script),
          }}
        />
      )}
    </>
  );
};

function generateInlineScript(script: string | Function): string {
  if (typeof script === 'function') {
    return `${script.toString()}()`;
  }
  return String(script);
}

export default AmpScript;
